---
- name: Ensure hostname is set
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install common packages
  apt:
    name:
      - curl
      - vim
      - git
    state: present
    update_cache: yes
